### ISSUE TITLE
Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

### ISSUE THREAD

**Issue by TomJansen** [mhsjlw/AndroidSnap#4]
Hello! When I am trying to run this application in Android Studio, I get the aforementioned error.

Here is a logcat

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: me.keegan.snap, PID: 4947
                  java.lang.RuntimeException: Unable to create application me.keegan.snap.SnapApplication: java.lang.RuntimeException: java.net.MalformedURLException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5794)
                      at android.app.ActivityThread.-wrap1(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                   Caused by: java.lang.RuntimeException: java.net.MalformedURLException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                      at com.parse.Parse.initialize(Parse.java:377)
                      at com.parse.Parse.initialize(Parse.java:355)
                      at me.keegan.snap.SnapApplication.onCreate(SnapApplication.java:12)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
                      at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6541) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
                   Caused by: java.net.MalformedURLException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                      at java.net.URL.<init>(URL.java:624)
                      at java.net.URL.<init>(URL.java:487)
                      at java.net.URL.<init>(URL.java:436)
                      at com.parse.Parse.initialize(Parse.java:375)
                      at com.parse.Parse.initialize(Parse.java:355) 
                      at me.keegan.snap.SnapApplication.onCreate(SnapApplication.java:12) 
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791) 
                      at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6541) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                      at java.net.URL.<init>(URL.java:529)
                      at java.net.URL.<init>(URL.java:487) 
                      at java.net.URL.<init>(URL.java:436) 
                      at com.parse.Parse.initialize(Parse.java:375) 
                      at com.parse.Parse.initialize(Parse.java:355) 
                      at me.keegan.snap.SnapApplication.onCreate(SnapApplication.java:12) 
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791) 
                      at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6541) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by mhsjlw** [comment]
Hi, did you make any changes to the code? If so, what constants did you change?

**Comment by TomJansen** [comment]
Nope, I did not change anything. Just downloaded from Github, imported and compiled in Android Studio. Maybe it has something to do with Gradle needed to sync?

**Comment by mhsjlw** [comment]
No, Parse has changed the way that they operate. To use this application, you must run a [Parse server](https://github.com/parse-community/parse-server). As well, you will need to modify this app to change the server endpoint, keys, etc. inside this app to connect to your personal Parse server.

I'll write instructions and actually test this eventually

**Comment by MarcVertigo** [comment]
I get the same error. Seems like this code base has potential. Disappointing there is not an installation guide.

**Comment by mhsjlw** [comment]
Fixed in #5, now requires the use of https://github.com/parse-community/parse-server
